# Generated by Django 4.2.11 on 2025-03-19 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0002_time_jogador_cpf_meutime_jogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogo',
            old_name='timeA_gol',
            new_name='timeA_gols',
        ),
        migrations.RenameField(
            model_name='jogo',
            old_name='timeB_gol',
            new_name='timeB_gols',
        ),
    ]
